//! Definition of tokens used in lexical analysis.

/// Tokens generated by lexical analysis.
#[derive(Debug, PartialEq)]
pub enum Token {
    /// Numeric literal
    Number(f64),
    /// `+`
    Plus,
    /// `-`
    Minus,
    /// `*`
    Star,
    /// `/`
    Slash,
    /// `(`
    LParen,
    /// `)`
    RParen,
}
